[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jp-imports"
version = "1.0"
dependencies = [
    "pandas~=2.2.2",
    "numpy~=2.0.1"
]
requires-python = ">=3.8"
authors = [
  {name = "Alejandro Ouslan", email = "dummy@example.com"},
]
maintainers = []
description = "Import/export data processing for Puerto Rico JP"
readme = "README.md"
license = {file = "LICENSE"}
keywords = []
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python"
]

[project.optional-dependencies]

[project.urls]
Repository = "https://github.com/ouslan/jp-imports"

[project.scripts]

[project.gui-scripts]

[project.entry-points."spam.magical"]