name: Run Unit Test via Pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]  # or "3.10"

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - name: Add Confluent APT Repository
        run: |
          echo "deb [arch=amd64] https://packages.confluent.io/deb/5.5 stable main" | sudo tee /etc/apt/sources.list.d/confluent.list
          curl -sSL https://packages.confluent.io/deb/5.5/KEY.gpg | sudo apt-key add -
          sudo apt-get update
      - name: Install system dependencies
        run: |
          sudo apt-get install -y libarrow-dev libparquet-dev
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi  
          pip install pyarrow  # Explicitly install pyarrow
      - name: Lint with Ruff  
        run: |  
          pip install ruff  
          ruff --format=github --target-version=py310 .  
        continue-on-error: true  
      - name: Test with pytest  
        run: |  
          pytest -v -s  
